import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./mdx-components.tsx",
  ],
  theme: {
    screens: {
      xs: "475px",
      ...defaultTheme.screens,
    },
    extend: {
      colors: {
        fore: "var(--col-fore)",
        back: "var(--col-back)",
      },
      fontFamily: {
        title: ["var(--font-urbanist)"],
        mono: ["var(--font-fira-mono)"],
        sans: ["var(--font-nunito)"],
        serif: ["var(--font-playfair-display)"],
      },
      boxShadow: {
        blocky: "10px 10px 0 var(--col-fore)",
        button: "5px 5px 0 var(--col-fore)",
        buttonhover: "3px 3px 0 var(--col-fore)",
      },
      animation: {
        blinky: "blinky 800ms step-end 10",
      },
      keyframes: {
        blinky: {
          "0%, 100%": {
            background: "var(--col-fore)",
            color: "var(--col-back)",
          },
          "50%": { background: "var(--col-back)", color: "var(--col-fore)" },
        },
      },
      spacing: {
        ggpn: "calc(var(--bg-grid-gap))",
        ggpy: "calc(var(--bg-grid-gap) * 2)",
        g01n: "calc(var(--bg-grid-box-size) * (1 / 8))",
        g01y: "calc(var(--bg-grid-box-size) * (1 / 8) + var(--bg-grid-gap))",
        g02n: "calc(var(--bg-grid-box-size) * (2 / 8))",
        g02y: "calc(var(--bg-grid-box-size) * (2 / 8) + var(--bg-grid-gap))",
        g03n: "calc(var(--bg-grid-box-size) * (3 / 8))",
        g03y: "calc(var(--bg-grid-box-size) * (3 / 8) + var(--bg-grid-gap))",
        g04n: "calc(var(--bg-grid-box-size) * (4 / 8))",
        g04y: "calc(var(--bg-grid-box-size) * (4 / 8) + var(--bg-grid-gap))",
        g05n: "calc(var(--bg-grid-box-size) * (5 / 8))",
        g05y: "calc(var(--bg-grid-box-size) * (5 / 8) + var(--bg-grid-gap))",
        g06n: "calc(var(--bg-grid-box-size) * (6 / 8))",
        g06y: "calc(var(--bg-grid-box-size) * (6 / 8) + var(--bg-grid-gap))",
        g07n: "calc(var(--bg-grid-box-size) * (7 / 8))",
        g07y: "calc(var(--bg-grid-box-size) * (7 / 8) + var(--bg-grid-gap))",
        g10n: "calc(var(--bg-grid-box-size))",
        g10t: "calc(var(--bg-grid-box-size) + 1 * var(--bg-grid-gap))",
        g10y: "calc(var(--bg-grid-box-size) + 2 * var(--bg-grid-gap))",
        g11n: "calc(var(--bg-grid-box-size) * (9 / 8))",
        g11t: "calc(var(--bg-grid-box-size) * (9 / 8) + 1 * var(--bg-grid-gap))",
        g11y: "calc(var(--bg-grid-box-size) * (9 / 8) + 2 * var(--bg-grid-gap))",
        g12n: "calc(var(--bg-grid-box-size) * (10 / 8))",
        g12t: "calc(var(--bg-grid-box-size) * (10 / 8) + 1 * var(--bg-grid-gap))",
        g12y: "calc(var(--bg-grid-box-size) * (10 / 8) + 2 * var(--bg-grid-gap))",
        g13n: "calc(var(--bg-grid-box-size) * (11 / 8))",
        g13t: "calc(var(--bg-grid-box-size) * (11 / 8) + 1 * var(--bg-grid-gap))",
        g13y: "calc(var(--bg-grid-box-size) * (11 / 8) + 2 * var(--bg-grid-gap))",
        g14n: "calc(var(--bg-grid-box-size) * (12 / 8))",
        g14t: "calc(var(--bg-grid-box-size) * (12 / 8) + 1 * var(--bg-grid-gap))",
        g14y: "calc(var(--bg-grid-box-size) * (12 / 8) + 2 * var(--bg-grid-gap))",
        g15n: "calc(var(--bg-grid-box-size) * (13 / 8))",
        g15t: "calc(var(--bg-grid-box-size) * (13 / 8) + 1 * var(--bg-grid-gap))",
        g15y: "calc(var(--bg-grid-box-size) * (13 / 8) + 2 * var(--bg-grid-gap))",
        g16n: "calc(var(--bg-grid-box-size) * (14 / 8))",
        g16t: "calc(var(--bg-grid-box-size) * (14 / 8) + 1 * var(--bg-grid-gap))",
        g16y: "calc(var(--bg-grid-box-size) * (14 / 8) + 2 * var(--bg-grid-gap))",
        g17n: "calc(var(--bg-grid-box-size) * (15 / 8))",
        g17t: "calc(var(--bg-grid-box-size) * (15 / 8) + 1 * var(--bg-grid-gap))",
        g17y: "calc(var(--bg-grid-box-size) * (15 / 8) + 2 * var(--bg-grid-gap))",
        g20n: "calc(var(--bg-grid-box-size) * 2)",
        g20y: "calc(var(--bg-grid-box-size) * 2 + 3 * var(--bg-grid-gap))",
        g30n: "calc(var(--bg-grid-box-size) * 3)",
        g30y: "calc(var(--bg-grid-box-size) * 3 + 4 * var(--bg-grid-gap))",
        g40n: "calc(var(--bg-grid-box-size) * 4)",
        g40y: "calc(var(--bg-grid-box-size) * 4 + 5 * var(--bg-grid-gap))",
        g50n: "calc(var(--bg-grid-box-size) * 5)",
        g50y: "calc(var(--bg-grid-box-size) * 5 + 6 * var(--bg-grid-gap))",
      },
      minWidth: {
        ggpn: "var(--bg-grid-gap)",
        ggpy: "calc(var(--bg-grid-gap) * 2)",
        g01n: "calc(var(--bg-grid-box-size) * (1 / 8))",
        g01y: "calc(var(--bg-grid-box-size) * (1 / 8) + var(--bg-grid-gap))",
        g02n: "calc(var(--bg-grid-box-size) * (2 / 8))",
        g02y: "calc(var(--bg-grid-box-size) * (2 / 8) + var(--bg-grid-gap))",
        g03n: "calc(var(--bg-grid-box-size) * (3 / 8))",
        g03y: "calc(var(--bg-grid-box-size) * (3 / 8) + var(--bg-grid-gap))",
        g04n: "calc(var(--bg-grid-box-size) * (4 / 8))",
        g04y: "calc(var(--bg-grid-box-size) * (4 / 8) + var(--bg-grid-gap))",
        g05n: "calc(var(--bg-grid-box-size) * (5 / 8))",
        g05y: "calc(var(--bg-grid-box-size) * (5 / 8) + var(--bg-grid-gap))",
        g06n: "calc(var(--bg-grid-box-size) * (6 / 8))",
        g06y: "calc(var(--bg-grid-box-size) * (6 / 8) + var(--bg-grid-gap))",
        g07n: "calc(var(--bg-grid-box-size) * (7 / 8))",
        g07y: "calc(var(--bg-grid-box-size) * (7 / 8) + var(--bg-grid-gap))",
        g10n: "calc(var(--bg-grid-box-size))",
        g10t: "calc(var(--bg-grid-box-size) + 1 * var(--bg-grid-gap))",
        g10y: "calc(var(--bg-grid-box-size) + 2 * var(--bg-grid-gap))",
        g11n: "calc(var(--bg-grid-box-size) * (9 / 8))",
        g11t: "calc(var(--bg-grid-box-size) * (9 / 8) + 1 * var(--bg-grid-gap))",
        g11y: "calc(var(--bg-grid-box-size) * (9 / 8) + 2 * var(--bg-grid-gap))",
        g12n: "calc(var(--bg-grid-box-size) * (10 / 8))",
        g12t: "calc(var(--bg-grid-box-size) * (10 / 8) + 1 * var(--bg-grid-gap))",
        g12y: "calc(var(--bg-grid-box-size) * (10 / 8) + 2 * var(--bg-grid-gap))",
        g13n: "calc(var(--bg-grid-box-size) * (11 / 8))",
        g13t: "calc(var(--bg-grid-box-size) * (11 / 8) + 1 * var(--bg-grid-gap))",
        g13y: "calc(var(--bg-grid-box-size) * (11 / 8) + 2 * var(--bg-grid-gap))",
        g14n: "calc(var(--bg-grid-box-size) * (12 / 8))",
        g14t: "calc(var(--bg-grid-box-size) * (12 / 8) + 1 * var(--bg-grid-gap))",
        g14y: "calc(var(--bg-grid-box-size) * (12 / 8) + 2 * var(--bg-grid-gap))",
        g15n: "calc(var(--bg-grid-box-size) * (13 / 8))",
        g15t: "calc(var(--bg-grid-box-size) * (13 / 8) + 1 * var(--bg-grid-gap))",
        g15y: "calc(var(--bg-grid-box-size) * (13 / 8) + 2 * var(--bg-grid-gap))",
        g16n: "calc(var(--bg-grid-box-size) * (14 / 8))",
        g16t: "calc(var(--bg-grid-box-size) * (14 / 8) + 1 * var(--bg-grid-gap))",
        g16y: "calc(var(--bg-grid-box-size) * (14 / 8) + 2 * var(--bg-grid-gap))",
        g17n: "calc(var(--bg-grid-box-size) * (15 / 8))",
        g17t: "calc(var(--bg-grid-box-size) * (15 / 8) + 1 * var(--bg-grid-gap))",
        g17y: "calc(var(--bg-grid-box-size) * (15 / 8) + 2 * var(--bg-grid-gap))",
        g20n: "calc(var(--bg-grid-box-size) * 2)",
        g20y: "calc(var(--bg-grid-box-size) * 2 + 3 * var(--bg-grid-gap))",
        g30n: "calc(var(--bg-grid-box-size) * 3)",
        g30y: "calc(var(--bg-grid-box-size) * 3 + 4 * var(--bg-grid-gap))",
        g40n: "calc(var(--bg-grid-box-size) * 4)",
        g40y: "calc(var(--bg-grid-box-size) * 4 + 5 * var(--bg-grid-gap))",
        g50n: "calc(var(--bg-grid-box-size) * 5)",
        g50y: "calc(var(--bg-grid-box-size) * 5 + 6 * var(--bg-grid-gap))",
      },
      width: {
        ggpn: "var(--bg-grid-gap)",
        ggpy: "calc(var(--bg-grid-gap) * 2)",
        g01n: "calc(var(--bg-grid-box-size) * (1 / 8))",
        g01y: "calc(var(--bg-grid-box-size) * (1 / 8) + var(--bg-grid-gap))",
        g02n: "calc(var(--bg-grid-box-size) * (2 / 8))",
        g02y: "calc(var(--bg-grid-box-size) * (2 / 8) + var(--bg-grid-gap))",
        g03n: "calc(var(--bg-grid-box-size) * (3 / 8))",
        g03y: "calc(var(--bg-grid-box-size) * (3 / 8) + var(--bg-grid-gap))",
        g04n: "calc(var(--bg-grid-box-size) * (4 / 8))",
        g04y: "calc(var(--bg-grid-box-size) * (4 / 8) + var(--bg-grid-gap))",
        g05n: "calc(var(--bg-grid-box-size) * (5 / 8))",
        g05y: "calc(var(--bg-grid-box-size) * (5 / 8) + var(--bg-grid-gap))",
        g06n: "calc(var(--bg-grid-box-size) * (6 / 8))",
        g06y: "calc(var(--bg-grid-box-size) * (6 / 8) + var(--bg-grid-gap))",
        g07n: "calc(var(--bg-grid-box-size) * (7 / 8))",
        g07y: "calc(var(--bg-grid-box-size) * (7 / 8) + var(--bg-grid-gap))",
        g10n: "calc(var(--bg-grid-box-size))",
        g10t: "calc(var(--bg-grid-box-size) + 1 * var(--bg-grid-gap))",
        g10y: "calc(var(--bg-grid-box-size) + 2 * var(--bg-grid-gap))",
        g11n: "calc(var(--bg-grid-box-size) * (9 / 8))",
        g11t: "calc(var(--bg-grid-box-size) * (9 / 8) + 1 * var(--bg-grid-gap))",
        g11y: "calc(var(--bg-grid-box-size) * (9 / 8) + 2 * var(--bg-grid-gap))",
        g12n: "calc(var(--bg-grid-box-size) * (10 / 8))",
        g12t: "calc(var(--bg-grid-box-size) * (10 / 8) + 1 * var(--bg-grid-gap))",
        g12y: "calc(var(--bg-grid-box-size) * (10 / 8) + 2 * var(--bg-grid-gap))",
        g13n: "calc(var(--bg-grid-box-size) * (11 / 8))",
        g13t: "calc(var(--bg-grid-box-size) * (11 / 8) + 1 * var(--bg-grid-gap))",
        g13y: "calc(var(--bg-grid-box-size) * (11 / 8) + 2 * var(--bg-grid-gap))",
        g14n: "calc(var(--bg-grid-box-size) * (12 / 8))",
        g14t: "calc(var(--bg-grid-box-size) * (12 / 8) + 1 * var(--bg-grid-gap))",
        g14y: "calc(var(--bg-grid-box-size) * (12 / 8) + 2 * var(--bg-grid-gap))",
        g15n: "calc(var(--bg-grid-box-size) * (13 / 8))",
        g15t: "calc(var(--bg-grid-box-size) * (13 / 8) + 1 * var(--bg-grid-gap))",
        g15y: "calc(var(--bg-grid-box-size) * (13 / 8) + 2 * var(--bg-grid-gap))",
        g16n: "calc(var(--bg-grid-box-size) * (14 / 8))",
        g16t: "calc(var(--bg-grid-box-size) * (14 / 8) + 1 * var(--bg-grid-gap))",
        g16y: "calc(var(--bg-grid-box-size) * (14 / 8) + 2 * var(--bg-grid-gap))",
        g17n: "calc(var(--bg-grid-box-size) * (15 / 8))",
        g17t: "calc(var(--bg-grid-box-size) * (15 / 8) + 1 * var(--bg-grid-gap))",
        g17y: "calc(var(--bg-grid-box-size) * (15 / 8) + 2 * var(--bg-grid-gap))",
        g20n: "calc(var(--bg-grid-box-size) * 2)",
        g20y: "calc(var(--bg-grid-box-size) * 2 + 3 * var(--bg-grid-gap))",
        g30n: "calc(var(--bg-grid-box-size) * 3)",
        g30y: "calc(var(--bg-grid-box-size) * 3 + 4 * var(--bg-grid-gap))",
        g40n: "calc(var(--bg-grid-box-size) * 4)",
        g40y: "calc(var(--bg-grid-box-size) * 4 + 5 * var(--bg-grid-gap))",
        g50n: "calc(var(--bg-grid-box-size) * 5)",
        g50y: "calc(var(--bg-grid-box-size) * 5 + 6 * var(--bg-grid-gap))",
      },
      minHeight: {
        ggpn: "var(--bg-grid-gap)",
        ggpy: "calc(var(--bg-grid-gap) * 2)",
        g01n: "calc(var(--bg-grid-box-size) * (1 / 8))",
        g01y: "calc(var(--bg-grid-box-size) * (1 / 8) + var(--bg-grid-gap))",
        g02n: "calc(var(--bg-grid-box-size) * (2 / 8))",
        g02y: "calc(var(--bg-grid-box-size) * (2 / 8) + var(--bg-grid-gap))",
        g03n: "calc(var(--bg-grid-box-size) * (3 / 8))",
        g03y: "calc(var(--bg-grid-box-size) * (3 / 8) + var(--bg-grid-gap))",
        g04n: "calc(var(--bg-grid-box-size) * (4 / 8))",
        g04y: "calc(var(--bg-grid-box-size) * (4 / 8) + var(--bg-grid-gap))",
        g05n: "calc(var(--bg-grid-box-size) * (5 / 8))",
        g05y: "calc(var(--bg-grid-box-size) * (5 / 8) + var(--bg-grid-gap))",
        g06n: "calc(var(--bg-grid-box-size) * (6 / 8))",
        g06y: "calc(var(--bg-grid-box-size) * (6 / 8) + var(--bg-grid-gap))",
        g07n: "calc(var(--bg-grid-box-size) * (7 / 8))",
        g07y: "calc(var(--bg-grid-box-size) * (7 / 8) + var(--bg-grid-gap))",
        g10n: "calc(var(--bg-grid-box-size))",
        g10t: "calc(var(--bg-grid-box-size) + 1 * var(--bg-grid-gap))",
        g10y: "calc(var(--bg-grid-box-size) + 2 * var(--bg-grid-gap))",
        g11n: "calc(var(--bg-grid-box-size) * (9 / 8))",
        g11t: "calc(var(--bg-grid-box-size) * (9 / 8) + 1 * var(--bg-grid-gap))",
        g11y: "calc(var(--bg-grid-box-size) * (9 / 8) + 2 * var(--bg-grid-gap))",
        g12n: "calc(var(--bg-grid-box-size) * (10 / 8))",
        g12t: "calc(var(--bg-grid-box-size) * (10 / 8) + 1 * var(--bg-grid-gap))",
        g12y: "calc(var(--bg-grid-box-size) * (10 / 8) + 2 * var(--bg-grid-gap))",
        g13n: "calc(var(--bg-grid-box-size) * (11 / 8))",
        g13t: "calc(var(--bg-grid-box-size) * (11 / 8) + 1 * var(--bg-grid-gap))",
        g13y: "calc(var(--bg-grid-box-size) * (11 / 8) + 2 * var(--bg-grid-gap))",
        g14n: "calc(var(--bg-grid-box-size) * (12 / 8))",
        g14t: "calc(var(--bg-grid-box-size) * (12 / 8) + 1 * var(--bg-grid-gap))",
        g14y: "calc(var(--bg-grid-box-size) * (12 / 8) + 2 * var(--bg-grid-gap))",
        g15n: "calc(var(--bg-grid-box-size) * (13 / 8))",
        g15t: "calc(var(--bg-grid-box-size) * (13 / 8) + 1 * var(--bg-grid-gap))",
        g15y: "calc(var(--bg-grid-box-size) * (13 / 8) + 2 * var(--bg-grid-gap))",
        g16n: "calc(var(--bg-grid-box-size) * (14 / 8))",
        g16t: "calc(var(--bg-grid-box-size) * (14 / 8) + 1 * var(--bg-grid-gap))",
        g16y: "calc(var(--bg-grid-box-size) * (14 / 8) + 2 * var(--bg-grid-gap))",
        g17n: "calc(var(--bg-grid-box-size) * (15 / 8))",
        g17t: "calc(var(--bg-grid-box-size) * (15 / 8) + 1 * var(--bg-grid-gap))",
        g17y: "calc(var(--bg-grid-box-size) * (15 / 8) + 2 * var(--bg-grid-gap))",
        g20n: "calc(var(--bg-grid-box-size) * 2)",
        g20y: "calc(var(--bg-grid-box-size) * 2 + 3 * var(--bg-grid-gap))",
        g30n: "calc(var(--bg-grid-box-size) * 3)",
        g30y: "calc(var(--bg-grid-box-size) * 3 + 4 * var(--bg-grid-gap))",
        g40n: "calc(var(--bg-grid-box-size) * 4)",
        g40y: "calc(var(--bg-grid-box-size) * 4 + 5 * var(--bg-grid-gap))",
        g50n: "calc(var(--bg-grid-box-size) * 5)",
        g50y: "calc(var(--bg-grid-box-size) * 5 + 6 * var(--bg-grid-gap))",
      },
      height: {
        ggpn: "var(--bg-grid-gap)",
        ggpy: "calc(var(--bg-grid-gap) * 2)",
        g01n: "calc(var(--bg-grid-box-size) * (1 / 8))",
        g01y: "calc(var(--bg-grid-box-size) * (1 / 8) + var(--bg-grid-gap))",
        g02n: "calc(var(--bg-grid-box-size) * (2 / 8))",
        g02y: "calc(var(--bg-grid-box-size) * (2 / 8) + var(--bg-grid-gap))",
        g03n: "calc(var(--bg-grid-box-size) * (3 / 8))",
        g03y: "calc(var(--bg-grid-box-size) * (3 / 8) + var(--bg-grid-gap))",
        g04n: "calc(var(--bg-grid-box-size) * (4 / 8))",
        g04y: "calc(var(--bg-grid-box-size) * (4 / 8) + var(--bg-grid-gap))",
        g05n: "calc(var(--bg-grid-box-size) * (5 / 8))",
        g05y: "calc(var(--bg-grid-box-size) * (5 / 8) + var(--bg-grid-gap))",
        g06n: "calc(var(--bg-grid-box-size) * (6 / 8))",
        g06y: "calc(var(--bg-grid-box-size) * (6 / 8) + var(--bg-grid-gap))",
        g07n: "calc(var(--bg-grid-box-size) * (7 / 8))",
        g07y: "calc(var(--bg-grid-box-size) * (7 / 8) + var(--bg-grid-gap))",
        g10n: "calc(var(--bg-grid-box-size))",
        g10t: "calc(var(--bg-grid-box-size) + 1 * var(--bg-grid-gap))",
        g10y: "calc(var(--bg-grid-box-size) + 2 * var(--bg-grid-gap))",
        g11n: "calc(var(--bg-grid-box-size) * (9 / 8))",
        g11t: "calc(var(--bg-grid-box-size) * (9 / 8) + 1 * var(--bg-grid-gap))",
        g11y: "calc(var(--bg-grid-box-size) * (9 / 8) + 2 * var(--bg-grid-gap))",
        g12n: "calc(var(--bg-grid-box-size) * (10 / 8))",
        g12t: "calc(var(--bg-grid-box-size) * (10 / 8) + 1 * var(--bg-grid-gap))",
        g12y: "calc(var(--bg-grid-box-size) * (10 / 8) + 2 * var(--bg-grid-gap))",
        g13n: "calc(var(--bg-grid-box-size) * (11 / 8))",
        g13t: "calc(var(--bg-grid-box-size) * (11 / 8) + 1 * var(--bg-grid-gap))",
        g13y: "calc(var(--bg-grid-box-size) * (11 / 8) + 2 * var(--bg-grid-gap))",
        g14n: "calc(var(--bg-grid-box-size) * (12 / 8))",
        g14t: "calc(var(--bg-grid-box-size) * (12 / 8) + 1 * var(--bg-grid-gap))",
        g14y: "calc(var(--bg-grid-box-size) * (12 / 8) + 2 * var(--bg-grid-gap))",
        g15n: "calc(var(--bg-grid-box-size) * (13 / 8))",
        g15t: "calc(var(--bg-grid-box-size) * (13 / 8) + 1 * var(--bg-grid-gap))",
        g15y: "calc(var(--bg-grid-box-size) * (13 / 8) + 2 * var(--bg-grid-gap))",
        g16n: "calc(var(--bg-grid-box-size) * (14 / 8))",
        g16t: "calc(var(--bg-grid-box-size) * (14 / 8) + 1 * var(--bg-grid-gap))",
        g16y: "calc(var(--bg-grid-box-size) * (14 / 8) + 2 * var(--bg-grid-gap))",
        g17n: "calc(var(--bg-grid-box-size) * (15 / 8))",
        g17t: "calc(var(--bg-grid-box-size) * (15 / 8) + 1 * var(--bg-grid-gap))",
        g17y: "calc(var(--bg-grid-box-size) * (15 / 8) + 2 * var(--bg-grid-gap))",
        g20n: "calc(var(--bg-grid-box-size) * 2)",
        g20y: "calc(var(--bg-grid-box-size) * 2 + 3 * var(--bg-grid-gap))",
        g30n: "calc(var(--bg-grid-box-size) * 3)",
        g30y: "calc(var(--bg-grid-box-size) * 3 + 4 * var(--bg-grid-gap))",
        g40n: "calc(var(--bg-grid-box-size) * 4)",
        g40y: "calc(var(--bg-grid-box-size) * 4 + 5 * var(--bg-grid-gap))",
        g50n: "calc(var(--bg-grid-box-size) * 5)",
        g50y: "calc(var(--bg-grid-box-size) * 5 + 6 * var(--bg-grid-gap))",
      },
      gap: {
        ggpn: "var(--bg-grid-gap)",
        ggpy: "calc(var(--bg-grid-gap) * 2)",
        g01n: "calc(var(--bg-grid-box-size) * (1 / 8))",
        g01y: "calc(var(--bg-grid-box-size) * (1 / 8) + var(--bg-grid-gap))",
        g02n: "calc(var(--bg-grid-box-size) * (2 / 8))",
        g02y: "calc(var(--bg-grid-box-size) * (2 / 8) + var(--bg-grid-gap))",
        g03n: "calc(var(--bg-grid-box-size) * (3 / 8))",
        g03y: "calc(var(--bg-grid-box-size) * (3 / 8) + var(--bg-grid-gap))",
        g04n: "calc(var(--bg-grid-box-size) * (4 / 8))",
        g04y: "calc(var(--bg-grid-box-size) * (4 / 8) + var(--bg-grid-gap))",
        g05n: "calc(var(--bg-grid-box-size) * (5 / 8))",
        g05y: "calc(var(--bg-grid-box-size) * (5 / 8) + var(--bg-grid-gap))",
        g06n: "calc(var(--bg-grid-box-size) * (6 / 8))",
        g06y: "calc(var(--bg-grid-box-size) * (6 / 8) + var(--bg-grid-gap))",
        g07n: "calc(var(--bg-grid-box-size) * (7 / 8))",
        g07y: "calc(var(--bg-grid-box-size) * (7 / 8) + var(--bg-grid-gap))",
        g10n: "calc(var(--bg-grid-box-size))",
        g10t: "calc(var(--bg-grid-box-size) + 1 * var(--bg-grid-gap))",
        g10y: "calc(var(--bg-grid-box-size) + 2 * var(--bg-grid-gap))",
        g11n: "calc(var(--bg-grid-box-size) * (9 / 8))",
        g11t: "calc(var(--bg-grid-box-size) * (9 / 8) + 1 * var(--bg-grid-gap))",
        g11y: "calc(var(--bg-grid-box-size) * (9 / 8) + 2 * var(--bg-grid-gap))",
        g12n: "calc(var(--bg-grid-box-size) * (10 / 8))",
        g12t: "calc(var(--bg-grid-box-size) * (10 / 8) + 1 * var(--bg-grid-gap))",
        g12y: "calc(var(--bg-grid-box-size) * (10 / 8) + 2 * var(--bg-grid-gap))",
        g13n: "calc(var(--bg-grid-box-size) * (11 / 8))",
        g13t: "calc(var(--bg-grid-box-size) * (11 / 8) + 1 * var(--bg-grid-gap))",
        g13y: "calc(var(--bg-grid-box-size) * (11 / 8) + 2 * var(--bg-grid-gap))",
        g14n: "calc(var(--bg-grid-box-size) * (12 / 8))",
        g14t: "calc(var(--bg-grid-box-size) * (12 / 8) + 1 * var(--bg-grid-gap))",
        g14y: "calc(var(--bg-grid-box-size) * (12 / 8) + 2 * var(--bg-grid-gap))",
        g15n: "calc(var(--bg-grid-box-size) * (13 / 8))",
        g15t: "calc(var(--bg-grid-box-size) * (13 / 8) + 1 * var(--bg-grid-gap))",
        g15y: "calc(var(--bg-grid-box-size) * (13 / 8) + 2 * var(--bg-grid-gap))",
        g16n: "calc(var(--bg-grid-box-size) * (14 / 8))",
        g16t: "calc(var(--bg-grid-box-size) * (14 / 8) + 1 * var(--bg-grid-gap))",
        g16y: "calc(var(--bg-grid-box-size) * (14 / 8) + 2 * var(--bg-grid-gap))",
        g17n: "calc(var(--bg-grid-box-size) * (15 / 8))",
        g17t: "calc(var(--bg-grid-box-size) * (15 / 8) + 1 * var(--bg-grid-gap))",
        g17y: "calc(var(--bg-grid-box-size) * (15 / 8) + 2 * var(--bg-grid-gap))",
        g20n: "calc(var(--bg-grid-box-size) * 2)",
        g20y: "calc(var(--bg-grid-box-size) * 2 + 3 * var(--bg-grid-gap))",
        g30n: "calc(var(--bg-grid-box-size) * 3)",
        g30y: "calc(var(--bg-grid-box-size) * 3 + 4 * var(--bg-grid-gap))",
        g40n: "calc(var(--bg-grid-box-size) * 4)",
        g40y: "calc(var(--bg-grid-box-size) * 4 + 5 * var(--bg-grid-gap))",
        g50n: "calc(var(--bg-grid-box-size) * 5)",
        g50y: "calc(var(--bg-grid-box-size) * 5 + 6 * var(--bg-grid-gap))",
      },
    },
  },
};
